### ISSUE TITLE
ReLU and MaxPool layer in block 1 of Res101

### ISSUE THREAD

**Issue by Feynman27** [kuangliu/pytorch-fpn#2]
I noticed you removed the relu and max-pooling layer before res-block 2 (compare [this](https://github.com/kuangliu/pytorch-fpn/blob/d88b68382823696ad83b57499ba2655c74307bcd/fpn.py#L47) and [this](https://github.com/pytorch/vision/blob/9834c99c2eb29015d308f30e440368138c59f92e/torchvision/models/resnet.py#L104-L105). Is there a reason why?

**Comment by Feynman27** [comment]
I see you add it in the `forward` call. [here] (https://github.com/kuangliu/pytorch-fpn/blob/d88b68382823696ad83b57499ba2655c74307bcd/fpn.py#L98-L99). Closing the issue.

**Comment by nanhui69** [comment]
> I see you add it in the `forward` call. [here] (
> 
> https://github.com/kuangliu/pytorch-fpn/blob/d88b68382823696ad83b57499ba2655c74307bcd/fpn.py#L98-L99
> 
> ). Closing the issue.

yeah ，it‘s right and further more did you check fpn base code reproduction was right?
