### ISSUE TITLE
Understanding fpn.py with picture

### ISSUE THREAD

**Issue by junha1125** [kuangliu/pytorch-fpn#6]
![picture1](https://user-images.githubusercontent.com/46951365/77819391-da60f900-711d-11ea-95a4-68e02f0f676a.jpg)

I recently got into machine learning study. Your code, fpn.py, helped me understand feature pyramid networks. When I studyed fpn.py, I was drawing network structure. Since I also want to help others figure out the code, I share my note.

**Comment by 300LiterPropofol** [comment]
Great work!
I was wondering which resnet this repo's author was using for this FPN, is it Resnet101? Can you tell me?

**Comment by junha1125** [comment]
I am not sure but I think it is not Resnet101. 
From layer1, Layer4 To Toplayer in the Image, there are only (8*3)+1 conv layers, not 101 layers, with shortcut that is the biggest peculiarity of Resnet. 

ps. 
(8*3) == A, B respectively in the Image has 3 conv layers.
1 == 'top layer' has 1 conv layers.

**Comment by 300LiterPropofol** [comment]
Thank you very much for your reply! Yes I agree with your opinion, doesn't seem like Resnet101.
